remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme

title: bad hypothesis
description: my thoughts on things that keep me up at night. I am pretty sure you got here accidentally, but here is a gif that describes you at this very moment 



<img src= "https://i.kym-cdn.com/photos/images/newsfeed/001/042/619/4ea.jpg" width= "300px">
